services:
  - docker

language: go

env:
  - DEP_VERSION="0.5.0"
  - IMAGE_TAG=`echo $TRAVIS_TAG|sed s/v//`

go:
  - 1.10.x

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y rpm
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep

go_import_path: github.com/ncabatoff/process-exporter

install:
  - dep ensure

script:
  - make style vet test build integ docker

after_success:
  - docker login -u $DOCKER_USER -p "$DOCKER_PASSWORD"
  - >
    test -n "$TRAVIS_TAG" && 
    docker tag ncabatoff/process-exporter:$IMAGE_TAG ncabatoff/process-exporter:latest && 
    docker push ncabatoff/process-exporter:$IMAGE_TAG && 
    docker push ncabatoff/process-exporter:latest && 
    curl -sL http://git.io/goreleaser | bash
